name: ConvNextV2_baseline
gpu_ids: [0]
job_dir: exp_cls_256_cls_retrain_with9
token: ""

network_G:
  which_model_G: convnextv2_baseline
  in_nc: 3
  out_nc: 7

datasets:
  train:
    type: train
    name: Osteosarcoma
    mode: classification
    image_dir: /home/user01/aiotlab/nmduong/BoneTumor/RAW/REAL_WSIs/training_data_256/images
    label_map: /home/user01/aiotlab/nmduong/BoneTumor/RAW/REAL_WSIs/dataset_split_256_by_class_retrain_with9.json
    label_dir: /home/user01/aiotlab/nmduong/BoneTumor/RAW/REAL_WSIs/training_data_256/labels
    height: 1024
    width: 1024
    batch_size: 256
    balance: False
    augment: true
    n_workers: 4

  valid:
    type: valid
    name: Osteosarcoma
    mode: classification
    image_dir: /home/user01/aiotlab/nmduong/BoneTumor/RAW/REAL_WSIs/training_data_256/images
    label_map: /home/user01/aiotlab/nmduong/BoneTumor/RAW/REAL_WSIs/dataset_split_256_by_class_retrain_with9.json
    label_dir: /home/user01/aiotlab/nmduong/BoneTumor/RAW/REAL_WSIs/training_data_256/labels
    height: 1024
    width: 1024
    batch_size: 2048
    augment: false
    n_workers: 4

  test:
    type: test
    name: Osteosarcoma
    mode: classification
    image_dir: /home/user01/aiotlab/nmduong/BoneTumor/RAW/REAL_WSIs/training_data_256/images
    label_map: /home/user01/aiotlab/nmduong/BoneTumor/RAW/REAL_WSIs/dataset_split_256_by_class_retrain_with9.json
    label_dir: /home/user01/aiotlab/nmduong/BoneTumor/RAW/REAL_WSIs/training_data_256/labels
    height: 1024
    width: 1024
    batch_size: 256
    balance: False
    augment: False

path:
  pretrain_model: ~

train:
  lr_G: !!float 5e-4
  beta1: 0.9
  beta2: 0.99
  epochs: 30
  eta_min: !!float 1e-7

  manual_seed: 2000
  val_freq: 1
  val_step_freq: 1000

  mode: classification

logger:
  print_freq: 20000
  save_checkpoint_freq: !!float 20000

is_train: true
is_test: false
wandb: true